# Generated by Django 4.2.4 on 2023-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('street', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('department', models.CharField(choices=[('ON', 'Onkologie'), ('NE', 'Neurologie'), ('HV', 'HV'), ('RE', 'Rezeptur'), ('SL', 'Sterillabor'), ('OP', 'Ophthalmologie')], default='ON', max_length=2)),
                ('case_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
